server:
  port: 8081
spring:  datasource:
    url: jdbc:mysql://localhost:3306/sakila
    username: root
    password: 1111
  jpa:    hibernate:      ddl-auto: update
    generate-ddl: false  
    show-sql: true
user:
   message: Hello User
      