server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sakila
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true  
    show-sql: true 